language: python
branches:
  only:
  - main
install:
- pip install -r requirements.txt
script:
- python3 -m pytest -v tests/test_dice.py
deploy:
  provider: heroku
  api_key:
    secure: aPLAS45yTjp5xkcsylD9m9kfkiyTPmYfafT26t78i5dqgSby7REFncbH8tm5vX621h1N9ds/3D9uX/ucg2vihj5vdn2h/kYdPvPZis+ax01MITJCHl6c2J5ThqqkvEheBX5Mt9okyArrtizhXAYpbNMjBvBJ0OSNBoXX3efmXjdCTf8tEX9m5kxYV43wLtqIKfUTkCEg1HQLUhEnacnAzwKVsTjGmi+XzrnkmrnsbG0qAcs+xb+qr2uKpdlVu3mrqte9gmZZfyyIeUwmZEYgD/cl8IDux5SegAcbVHKh2VWqH5S7ONCEyGkBP3EQEfXHc5H26izuxI60P+7wzf353KxmU2vniJ7xj4LJbeNkxrA7c3Ytlwzp6zuf0/zg/Q3mD+6TDj5OB4OnDeq+VhkXvmh159qoRE4qz6+SnwlqWgqsyZ9RjNfJPFNg+2P6PSCN4y+zpTeg0+IbSjO+Df8BDP8POcJZ6TK64VEJBk2a6kFVJbEfx4+oKO5rSy3lkFste8AxwQ+5p12JQu1FPA9Fy1+QRgNGLlLQ9TuwwK1BB2eN5lLH68i4fu0ROaIfZuFZggMFgMyAOFAOMoEpaeAxNBYPVIW3cnSgbiQhvTOTExJMObSt2UQFopu0itXPE1joLguB0GkARAEn/HVAG5ySeudzNgIC0H7+mHFRrzhqHbo=
  app:
    main: ci-pipeline-staging
    production: ci-pipeline-production
notifications:
  slack:
    secure: qygWa6yxOHiMDo0Kc+D7knedcpCkPHrw+zRSGIEX6Hr12mllk7Y1WbZ6SKpDSAvoPY9It2XRb39kl5J+pROr4tfn3aJ83QJOv/1QpPINWupWSiEiJeYzdMfbF5xrw1Hkj7jtEJxQT0LqKJQtup1fA7W/DxM+nUo6x1moY2mVFuZ2DU9stTDW87H74Z81yALeYArJX+hv0I2YBZ8PTN+nrovDKKr0l09UXHlOEsAhbUehg6q35faairQnWRvOzOPVYOyxQcCh7NiVtLsmhkE/q4akbj77AfSaHOjzBhC4Z0rA/t9cw8ELiFbKcjByYRp7GohamTw2uofj3+DgaXWOEhI0HPLLeYdsF6rc3lwg+bBKLmOlhrMzu/sLn8gNFghPaAbXcsMsMEKavDO8dFH2ibrHPjynsRhHWo4xQUORRapyj2buTGWn9cq+jEBVkGcIMP1h0018vBkHBQ6o5II44371dS0sPf2AelVkxBP84uEznN/5h1/7G04Z7ADtewSnNc/MIklVYllrJpkmkByjhcxXnfUEED+rA7JrdSs7BI3rNH6QnSDzWCYdY/d07Z+b2R+aTEPXFIuVCtRb8xNyBZgeG+2folKUdM8OGXmUiTJjfY61lp6lZSm+JZ5s9+57NDYXovaICxjslHmnfxWGGF7wGHFawOUZh9a02p6+YKE=
